# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:categories/:title
#collections:
#  projects:       
#  permalink:      /:categories/:title
#  output:         True
   


# Setup
title:            Sravan Patchala
tagline:          ''
description:      'My personal webpage'
url:              https://sravps7.github.io/
baseurl:          /
author:
  name:           'Sravan Patchala'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sravps7/sravps7.github.io
